// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: gun.proto

package gun_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hunk) Reset() {
	*x = Hunk{}
	mi := &file_gun_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hunk) ProtoMessage() {}

func (x *Hunk) ProtoReflect() protoreflect.Message {
	mi := &file_gun_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hunk.ProtoReflect.Descriptor instead.
func (*Hunk) Descriptor() ([]byte, []int) {
	return file_gun_proto_rawDescGZIP(), []int{0}
}

func (x *Hunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_gun_proto protoreflect.FileDescriptor

const file_gun_proto_rawDesc = "" +
	"\n" +
	"\tgun.proto\"\x1a\n" +
	"\x04Hunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2F\n" +
	"\n" +
	"GunService\x12\x17\n" +
	"\x03Tun\x12\x05.Hunk\x1a\x05.Hunk(\x010\x01\x12\x1f\n" +
	"\vTunDatagram\x12\x05.Hunk\x1a\x05.Hunk(\x010\x01B/Z-github.com/daeuniverse/outbound/pkg/gun_protob\x06proto3"

var (
	file_gun_proto_rawDescOnce sync.Once
	file_gun_proto_rawDescData []byte
)

func file_gun_proto_rawDescGZIP() []byte {
	file_gun_proto_rawDescOnce.Do(func() {
		file_gun_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gun_proto_rawDesc), len(file_gun_proto_rawDesc)))
	})
	return file_gun_proto_rawDescData
}

var file_gun_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gun_proto_goTypes = []any{
	(*Hunk)(nil), // 0: Hunk
}
var file_gun_proto_depIdxs = []int32{
	0, // 0: GunService.Tun:input_type -> Hunk
	0, // 1: GunService.TunDatagram:input_type -> Hunk
	0, // 2: GunService.Tun:output_type -> Hunk
	0, // 3: GunService.TunDatagram:output_type -> Hunk
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gun_proto_init() }
func file_gun_proto_init() {
	if File_gun_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gun_proto_rawDesc), len(file_gun_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gun_proto_goTypes,
		DependencyIndexes: file_gun_proto_depIdxs,
		MessageInfos:      file_gun_proto_msgTypes,
	}.Build()
	File_gun_proto = out.File
	file_gun_proto_goTypes = nil
	file_gun_proto_depIdxs = nil
}
